 /*
 *******************************************************************************
 * @file           : STD_TYPES.c
 * @author         : SARA SAAD MAHMOUD
 * @brief          : RCC INTERFACE HEADER file
 ******************************************************************************
*/

#ifndef INC_MCAL_RCC_RCC_INTERFACE_H_
#define INC_MCAL_RCC_RCC_INTERFACE_H_

/************************************* INCLUDE START ***********************************************************/

#include "../STD_TYPES.h"
#include "../MATH.h"
#include"RCC_config.h"
#include "RCC_private.h"

/************************************* INCLUDE START ***********************************************************/

/*************************************      MACRO START      ***********************************************************/
#define AHB2_OTGFS_PERIPHERAL   7


/* SYSTEM CLOCK SOURCE*/
#define	HSI_CLK_SRC 0
#define	HSE_CLK_SRC 1
#define	PLL_CLK_SRC 2

/* HSE CLK SOURCE*/
#define RC_HSE_CLK_SRC         1
#define CRYSTAL_HSE_CLK_SRC    0

/* PLL CLOCK SOURCE*/
#define PLL_HSI_CLK_SRC         0
#define PLL_HSE_CLK_SRC         1

/* ENABLE HSI*/
#define RCC_CR_HSION            0
#define RCC_CR_HSION_HSIRDY     1

/* ENABLE HSE*/
#define RCC_HSEBYP             18
#define RCC_HSEON              16
#define RCC_HSERDY             17

/*ENABLE PLL*/
#define PLL_PLLON     24
#define pllPLLRDY     25
#define PLLSRC        22

/* SYSTEM CLOCK SELECT*/
#define SW_0    0
#define SW_1    1


/*************************************      MACRO END      ***********************************************************/

/************************************* MACRO FUNCTION START***********************************************************/

#define GPIOA_PERIPHERAL_ENABLE()  ((RCC_REG -> RCC_AHB1ENR)|= (1<<GPIOA_PERIPHERAL))
#define GPIOB_PERIPHERAL_ENABLE()  ((RCC_REG -> RCC_AHB1ENR)|= (1<<GPIOB_PERIPHERAL))
#define GPIOC_PERIPHERAL_ENABLE()  ((RCC_REG -> RCC_AHB1ENR)|= (1<<GPIOC_PERIPHERAL))
#define GPIOD_PERIPHERAL_ENABLE()  ((RCC_REG -> RCC_AHB1ENR)|= (1<<GPIOD_PERIPHERAL))
#define GPIOE_PERIPHERAL_ENABLE()  ((RCC_REG -> RCC_AHB1ENR)|= (1<<GPIOE_PERIPHERAL))
#define GPIOH_PERIPHERAL_ENABLE()  ((RCC_REG -> RCC_AHB1ENR)|= (1<<GPIOH_PERIPHERAL))
#define CRC_PERIPHERAL_ENABLE()    ((RCC_REG -> RCC_AHB1ENR)|= (1<<CRC_PERIPHERAL))
#define DMA1_PERIPHERAL_ENABLE()   ((RCC_REG -> RCC_AHB1ENR)|= (1<<DMA1_PERIPHERAL))
#define DMA2_PERIPHERAL_ENABLE()   ((RCC_REG -> RCC_AHB1ENR)|= (1<<DMA2_PERIPHERAL))


#define GPIOA_PERIPHERAL_DISABLE()  ((RCC_REG -> RCC_AHB1ENR)&= ~(1<<GPIOA_PERIPHERAL))
#define GPIOB_PERIPHERAL_DISABLE()  ((RCC_REG -> RCC_AHB1ENR)&= ~(1<<GPIOB_PERIPHERAL))
#define GPIOC_PERIPHERAL_DISABLE()  ((RCC_REG -> RCC_AHB1ENR)&= ~(1<<GPIOC_PERIPHERAL))
#define GPIOD_PERIPHERAL_DISABLE()  ((RCC_REG -> RCC_AHB1ENR)&= ~(1<<GPIOD_PERIPHERAL))
#define GPIOE_PERIPHERAL_DISABLE()  ((RCC_REG -> RCC_AHB1ENR)&= ~(1<<GPIOE_PERIPHERAL))
#define GPIOH_PERIPHERAL_DISABLE()  ((RCC_REG -> RCC_AHB1ENR)&= ~(1<<GPIOH_PERIPHERAL))
#define CRC_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_AHB1ENR)&= ~(1<<CRC_PERIPHERAL))
#define DMA1_PERIPHERAL_DISABLE()   ((RCC_REG -> RCC_AHB1ENR)&= ~(1<<DMA1_PERIPHERAL))
#define DMA2_PERIPHERAL_DISABLE()   ((RCC_REG -> RCC_AHB1ENR)&= ~(1<<DMA2_PERIPHERAL))


#define OTGFS_PERIPHERAL_ENABLE()    ((RCC_REG -> RCC_AHB2ENR) |= (1<<AHB2_OTGFS_PERIPHERAL))
#define OTGFS_PERIPHERAL_DISABLE()   ((RCC_REG -> RCC_AHB2ENR) &= ~(1<<AHB2_OTGFS_PERIPHERAL))

#define TIM2_PERIPHERAL_ENABLE()     ((RCC_REG -> RCC_APB1ENR) |= (1<<TIM2_PERIPHERAL))
#define TIM3_PERIPHERAL_ENABLE()     ((RCC_REG -> RCC_APB1ENR) |= (1<<TIM3_PERIPHERAL))
#define TIM4_PERIPHERAL_ENABLE()     ((RCC_REG -> RCC_APB1ENR) |= (1<<TIM4_PERIPHERAL))
#define TIM5_PERIPHERAL_ENABLE()     ((RCC_REG -> RCC_APB1ENR) |= (1<<TIM5_PERIPHERAL))
#define WWDG_PERIPHERAL_ENABLE()     ((RCC_REG -> RCC_APB1ENR) |= (1<<WWDG_PERIPHERAL))
#define SPI2_PERIPHERAL_ENABLE()     ((RCC_REG -> RCC_APB1ENR) |= (1<<SPI2_PERIPHERAL))
#define SPI3_PERIPHERAL_ENABLE()     ((RCC_REG -> RCC_APB1ENR) |= (1<<SPI3_PERIPHERAL))
#define USART2_PERIPHERAL_ENABLE()   ((RCC_REG -> RCC_APB1ENR) |= (1<<USART2_PERIPHERAL))
#define I2C1_PERIPHERAL_ENABLE()     ((RCC_REG -> RCC_APB1ENR) |= (1<<I2C1_PERIPHERAL))
#define I2C2_PERIPHERAL_ENABLE()     ((RCC_REG -> RCC_APB1ENR) |= (1<<I2C2_PERIPHERAL))
#define I2C3_PERIPHERAL_ENABLE()     ((RCC_REG -> RCC_APB1ENR) |= (1<<I2C3_PERIPHERAL))
#define PWR_PERIPHERAL_ENABLE()      ((RCC_REG -> RCC_APB1ENR) |= (1<<PWR_PERIPHERAL))


#define TIM2_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_APB1ENR) &= ~(1<<TIM2_PERIPHERAL))
#define TIM3_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_APB1ENR) &= ~(1<<TIM3_PERIPHERAL))
#define TIM4_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_APB1ENR) &= ~(1<<TIM4_PERIPHERAL))
#define TIM5_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_APB1ENR) &= ~(1<<TIM5_PERIPHERAL))
#define WWDG_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_APB1ENR) &= ~(1<<WWDG_PERIPHERAL))
#define SPI2_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_APB1ENR) &= ~(1<<SPI2_PERIPHERAL))
#define SPI3_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_APB1ENR) &= ~(1<<SPI3_PERIPHERAL))
#define USART2_PERIPHERAL_DISABLE()  ((RCC_REG -> RCC_APB1ENR) &= ~(1<<USART2_PERIPHERAL))
#define I2C1_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_APB1ENR) &= ~(1<<I2C1_PERIPHERAL))
#define I2C2_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_APB1ENR) &= ~(1<<I2C2_PERIPHERAL))
#define I2C3_PERIPHERAL_DISABLE()    ((RCC_REG -> RCC_APB1ENR) &= ~(1<<I2C3_PERIPHERAL))
#define PWR_PERIPHERAL_DISABLE()     ((RCC_REG -> RCC_APB1ENR) &= ~(1<<PWR_PERIPHERAL))


#define TIM1_PERIPHERAL_ENABLE()    ((RCC_REG -> RCC_APB2ENR) |= (1<<TIM1_PERIPHERAL))
#define USART1_PERIPHERAL_ENABLE()  ((RCC_REG -> RCC_APB2ENR) |= (1<<USART1_PERIPHERAL))
#define USART6_PERIPHERAL_ENABLE()  ((RCC_REG -> RCC_APB2ENR) |= (1<<USART6_PERIPHERAL))
#define ADC1_PERIPHERAL_ENABLE()    ((RCC_REG -> RCC_APB2ENR) |= (1<<ADC1_PERIPHERAL))
#define SDIO_PERIPHERAL_ENABLE()    ((RCC_REG -> RCC_APB2ENR) |= (1<<SDIO_PERIPHERAL))
#define SPI1_PERIPHERAL_ENABLE()    ((RCC_REG -> RCC_APB2ENR) |= (1<<SPI1_PERIPHERAL))
#define SPI4_PERIPHERAL_ENABLE()    ((RCC_REG -> RCC_APB2ENR) |= (1<<SPI4_PERIPHERAL))
#define SYSCFG_PERIPHERAL_ENABLE()  ((RCC_REG -> RCC_APB2ENR) |= (1<<SYSCFG_PERIPHERAL))
#define TIM9_PERIPHERAL_ENABLE()    ((RCC_REG -> RCC_APB2ENR) |= (1<<TIM9_PERIPHERAL))
#define TIM10_PERIPHERAL_ENABLE()   ((RCC_REG -> RCC_APB2ENR) |= (1<<TIM10_PERIPHERAL))
#define TIM11_PERIPHERAL_ENABLE()   ((RCC_REG -> RCC_APB2ENR) |= (1<<TIM11_PERIPHERAL))


#define TIM1_PERIPHERAL_DISABLE()   ((RCC_REG -> RCC_APB2ENR) &= ~(1<<TIM1_PERIPHERAL))
#define USART1_PERIPHERAL_DISABLE() ((RCC_REG -> RCC_APB2ENR) &= ~(1<<USART1_PERIPHERAL))
#define USART6_PERIPHERAL_DISABLE() ((RCC_REG -> RCC_APB2ENR) &= ~(1<<USART6_PERIPHERAL))
#define ADC1_PERIPHERAL_DISABLE()   ((RCC_REG -> RCC_APB2ENR) &= ~(1<<ADC1_PERIPHERAL))
#define SDIO_PERIPHERAL_DISABLE()   ((RCC_REG -> RCC_APB2ENR) &= ~(1<<SDIO_PERIPHERAL))
#define SPI1_PERIPHERAL_DISABLE()   ((RCC_REG -> RCC_APB2ENR) &= ~(1<<SPI1_PERIPHERAL))
#define SPI4_PERIPHERAL_DISABLE()   ((RCC_REG -> RCC_APB2ENR) &= ~(1<<SPI4_PERIPHERAL))
#define SYSCFG_PERIPHERAL_DISABLE() ((RCC_REG -> RCC_APB2ENR) &= ~(1<<SYSCFG_PERIPHERAL))
#define TIM9_PERIPHERAL_DISABLE()   ((RCC_REG -> RCC_APB2ENR) &= ~(1<<TIM9_PERIPHERAL))
#define TIM10_PERIPHERAL_DISABLE()  ((RCC_REG -> RCC_APB2ENR) &= ~(1<<TIM10_PERIPHERAL))
#define TIM11_PERIPHERAL_DISABLE()  ((RCC_REG -> RCC_APB2ENR) &= ~(1<<TIM11_PERIPHERAL))

/************************************* MACRO FUNCTION END ***********************************************************/

/************************************* USER DATA TYPES START ***************************************************/
typedef enum
{
	AHB1 =0,
	AHB2,
	APB1,
	APB2,
}RCC_BUSS;

typedef enum
{
	GPIOA_PERIPHERAL=0,
	GPIOB_PERIPHERAL=1,
	GPIOC_PERIPHERAL=2,
	GPIOD_PERIPHERAL=3,
	GPIOE_PERIPHERAL=4,
	GPIOH_PERIPHERAL=7,
	CRC_PERIPHERAL=12,
	DMA1_PERIPHERAL=21,
	DMA2_PERIPHERAL=22,
}AHB1_PERIPHERALS;

typedef enum
{
	 TIM2_PERIPHERAL=0,
	 TIM3_PERIPHERAL=1,
	 TIM4_PERIPHERAL=2,
	 TIM5_PERIPHERAL=3,
	 WWDG_PERIPHERAL=11,
	 SPI2_PERIPHERAL=14,
	 SPI3_PERIPHERAL=15,
	 USART2_PERIPHERAL=17,
	 I2C1_PERIPHERAL=21,
	 I2C2_PERIPHERAL=22,
	 I2C3_PERIPHERAL=23,
	 PWR_PERIPHERAL=28,
}APB1_PERIPHERALS;

typedef enum
{
	 TIM1_PERIPHERAL=0,
	 USART1_PERIPHERAL=4,
	 USART6_PERIPHERAL=5,
	 ADC1_PERIPHERAL=8,
	 SDIO_PERIPHERAL=11,
	 SPI1_PERIPHERAL=12,
	 SPI4_PERIPHERAL=13,
	 SYSCFG_PERIPHERAL=14,
	 TIM9_PERIPHERAL=16,
	 TIM10_PERIPHERAL=17,
	 TIM11_PERIPHERAL=18,
}APB2_PERIPHERALS;

/************************************* USER DATA TYPES END     ***********************************************************/

/*********************************** FUNCTION PRPTOTYPE START  ***********************************************************/
STD_RETURN_TYPES RCC_INTIALIZE(void);
STD_RETURN_TYPES RCC_PERIPHERAL_ENABLE(RCC_BUSS _BUSS,uint32 _PERIPHERAL);
STD_RETURN_TYPES RCC_PERIPHERAL_DISABLE(RCC_BUSS _BUSS,uint32 _PERIPHERAL);
/************************************* FUNCTION PRPTOTYPE END  ***********************************************************/
#endif /* INC_MCAL_RCC_RCC_INTERFACE_H_ */
